# Generated by Django 5.2.6 on 2026-08-18 05:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('file_name', models.CharField(max_length=255, verbose_name='Dosya adı')),
                ('file_path', models.CharField(max_length=500, verbose_name='Dosya yolu')),
                ('kind', models.CharField(choices=[('manual', 'El ile'), ('scheduled', 'Zamanlanmış'), ('pre_restore', 'Geri yükleme öncesi'), ('pre_upgrade', 'Güncelleme öncesi')], default='manual', max_length=20, verbose_name='Tür')),
                ('status', models.CharField(choices=[('running', 'Alınıyor'), ('success', 'Başarılı'), ('failed', 'Başarısız'), ('verified', 'Doğrulandı'), ('corrupt', 'Bozuk')], db_index=True, default='running', max_length=20, verbose_name='Durum')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='Boyut (bayt)')),
                ('is_encrypted', models.BooleanField(default=True, verbose_name='Şifreli')),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA-256 özeti')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Başlangıç')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('app_version', models.CharField(blank=True, max_length=20, verbose_name='Uygulama sürümü')),
                ('database_engine', models.CharField(blank=True, max_length=40, verbose_name='Veritabanı')),
                ('record_counts', models.JSONField(blank=True, default=dict, verbose_name='Kayıt sayıları')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Doğrulama zamanı')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_created', to=settings.AUTH_USER_MODEL, verbose_name='Alan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Yedek kaydı',
                'verbose_name_plural': 'Yedek kayıtları',
                'ordering': ['-started_at'],
                'permissions': [('can_run_backup', 'Yedek alabilir'), ('can_restore_backup', 'Yedekten geri yükleyebilir'), ('can_configure_backup', 'Yedekleme ayarlarını değiştirebilir')],
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Ad')),
                ('frequency', models.CharField(choices=[('hourly', 'Saatlik'), ('daily', 'Günlük'), ('weekly', 'Haftalık')], default='daily', max_length=20, verbose_name='Sıklık')),
                ('run_at', models.TimeField(blank=True, null=True, verbose_name='Çalışma saati')),
                ('destination_dir', models.CharField(max_length=500, verbose_name='Hedef klasör')),
                ('retention_days', models.PositiveSmallIntegerField(default=30, verbose_name='Saklama süresi (gün)')),
                ('encrypt', models.BooleanField(default=True, verbose_name='Şifrele')),
                ('verify_after_backup', models.BooleanField(default=True, verbose_name='Yedek sonrası doğrula')),
                ('is_active', models.BooleanField(default=True, verbose_name='Etkin')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Son çalışma')),
                ('last_status', models.CharField(blank=True, max_length=40, verbose_name='Son durum')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Yedekleme planı',
                'verbose_name_plural': 'Yedekleme planları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RestoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('target', models.CharField(choices=[('production', 'Canlı veritabanı'), ('test', 'Test veritabanı')], default='test', max_length=20, verbose_name='Hedef')),
                ('target_path', models.CharField(blank=True, max_length=500, verbose_name='Hedef yol')),
                ('status', models.CharField(choices=[('pending', 'Onay bekliyor'), ('running', 'Yükleniyor'), ('success', 'Başarılı'), ('failed', 'Başarısız'), ('rolled_back', 'Geri alındı')], default='pending', max_length=20, verbose_name='Durum')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('verification_report', models.JSONField(blank=True, default=dict, verbose_name='Doğrulama raporu')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata')),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restores', to='accounts.approvalrequest', verbose_name='Onay')),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restores', to='backups.backuprecord', verbose_name='Yedek')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restores_requested', to=settings.AUTH_USER_MODEL, verbose_name='Talep eden')),
                ('safety_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_for_restores', to='backups.backuprecord', verbose_name='Güvenlik yedeği')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Geri yükleme kaydı',
                'verbose_name_plural': 'Geri yükleme kayıtları',
                'ordering': ['-created_at'],
            },
        ),
    ]
