# Generated by Django 5.2.6 on 2026-08-18 05:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Başlık')),
                ('feature', models.CharField(choices=[('sommelier', 'Sommelier asistanı'), ('pairing', 'Yemek–şarap eşleştirme'), ('report_query', 'Doğal dille rapor sorgulama'), ('forecast', 'Satış tahmini'), ('inventory', 'Stok ve satın alma önerisi'), ('waste', 'Fire / israf analizi'), ('anomaly', 'Anormal işlem tespiti'), ('customer', 'Müşteri tercih analizi'), ('menu_text', 'Menü açıklaması oluşturma'), ('translation', 'Çok dilli çeviri'), ('vision', 'Etiket / görsel analizi'), ('training', 'Personel eğitim asistanı'), ('decision', 'Yönetici karar desteği'), ('day_summary', 'Gün sonu yönetici özeti'), ('devstudio', 'AI Development Studio'), ('caio', 'CAIO ajanı'), ('other', 'Diğer')], default='sommelier', max_length=30, verbose_name='İşlev')),
                ('provider', models.CharField(blank=True, max_length=30, verbose_name='Sağlayıcı')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='Model')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Arşivlendi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Yapay zekâ sohbeti',
                'verbose_name_plural': 'Yapay zekâ sohbetleri',
                'ordering': ['-updated_at'],
                'permissions': [('can_use_cloud_ai', 'Bulut yapay zekâ sağlayıcısı kullanabilir'), ('can_configure_ai', 'Yapay zekâ ayarlarını değiştirebilir'), ('can_apply_ai_suggestion', 'Yapay zekâ önerisini uygulayabilir'), ('can_view_ai_costs', 'Yapay zekâ maliyetlerini görebilir')],
            },
        ),
        migrations.CreateModel(
            name='AICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('feature', models.CharField(choices=[('sommelier', 'Sommelier asistanı'), ('pairing', 'Yemek–şarap eşleştirme'), ('report_query', 'Doğal dille rapor sorgulama'), ('forecast', 'Satış tahmini'), ('inventory', 'Stok ve satın alma önerisi'), ('waste', 'Fire / israf analizi'), ('anomaly', 'Anormal işlem tespiti'), ('customer', 'Müşteri tercih analizi'), ('menu_text', 'Menü açıklaması oluşturma'), ('translation', 'Çok dilli çeviri'), ('vision', 'Etiket / görsel analizi'), ('training', 'Personel eğitim asistanı'), ('decision', 'Yönetici karar desteği'), ('day_summary', 'Gün sonu yönetici özeti'), ('devstudio', 'AI Development Studio'), ('caio', 'CAIO ajanı'), ('other', 'Diğer')], db_index=True, default='other', max_length=30, verbose_name='İşlev')),
                ('provider', models.CharField(db_index=True, max_length=30, verbose_name='Sağlayıcı')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='Model')),
                ('is_local_provider', models.BooleanField(default=True, verbose_name='Yerel sağlayıcı')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='İstem belirteci')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='Yanıt belirteci')),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=12, verbose_name='Tahmini maliyet (USD)')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='Gecikme (ms)')),
                ('outcome', models.CharField(choices=[('success', 'Başarılı'), ('failed', 'Başarısız'), ('fallback', 'Yedek sağlayıcıya geçildi'), ('cancelled', 'İptal edildi'), ('blocked', 'Politika gereği engellendi')], db_index=True, default='success', max_length=20, verbose_name='Sonuç')),
                ('error_type', models.CharField(blank=True, max_length=80, verbose_name='Hata türü')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata mesajı')),
                ('fallback_from', models.CharField(blank=True, max_length=30, verbose_name='Yedeklenen sağlayıcı')),
                ('pii_masked', models.BooleanField(default=False, verbose_name='Kişisel veri maskelendi')),
                ('masking_summary', models.CharField(blank=True, max_length=250, verbose_name='Maskeleme özeti')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Zaman')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_calls', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='aiservices.aiconversation', verbose_name='Sohbet')),
            ],
            options={
                'verbose_name': 'Yapay zekâ çağrı kaydı',
                'verbose_name_plural': 'Yapay zekâ çağrı kayıtları',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('role', models.CharField(choices=[('system', 'Sistem'), ('user', 'Kullanıcı'), ('assistant', 'Asistan')], max_length=20, verbose_name='Rol')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('masked_content', models.TextField(blank=True, help_text='Bulut sağlayıcıya fiilen gönderilen metin.', verbose_name='Maskelenmiş içerik')),
                ('masking_summary', models.CharField(blank=True, max_length=250, verbose_name='Maskeleme özeti')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='aiservices.aiconversation', verbose_name='Sohbet')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Yapay zekâ mesajı',
                'verbose_name_plural': 'Yapay zekâ mesajları',
                'ordering': ['conversation', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIQualityFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Kötü'), (2, 'Zayıf'), (3, 'İdare eder'), (4, 'İyi'), (5, 'Mükemmel')], verbose_name='Puan')),
                ('issue_tags', models.JSONField(blank=True, default=list, help_text="Örn: ['yanlış_bilgi', 'alakasız', 'çok_uzun', 'dil_hatası']", verbose_name='Sorun etiketleri')),
                ('comment', models.TextField(blank=True, verbose_name='Yorum')),
                ('call_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='aiservices.aicalllog', verbose_name='Çağrı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='aiservices.aimessage', verbose_name='Mesaj')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_feedback', to=settings.AUTH_USER_MODEL, verbose_name='Bildiren')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Yapay zekâ geri bildirimi',
                'verbose_name_plural': 'Yapay zekâ geri bildirimleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('kind', models.CharField(choices=[('wine_pairing', 'Şarap eşleştirmesi'), ('menu_description', 'Menü açıklaması'), ('tasting_note', 'Tadım notu'), ('purchase_order', 'Satın alma önerisi'), ('price_change', 'Fiyat değişikliği'), ('stock_adjustment', 'Stok düzeltmesi'), ('translation', 'Çeviri'), ('report_insight', 'Rapor içgörüsü'), ('code_change', 'Kod değişikliği'), ('other', 'Diğer')], db_index=True, max_length=30, verbose_name='Tür')),
                ('title', models.CharField(max_length=250, verbose_name='Başlık')),
                ('summary', models.TextField(blank=True, verbose_name='Özet')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Öneri verisi')),
                ('previous_state', models.JSONField(blank=True, default=dict, verbose_name='Önceki durum')),
                ('target_type', models.CharField(blank=True, max_length=100, verbose_name='Hedef türü')),
                ('target_id', models.CharField(blank=True, max_length=64, verbose_name='Hedef kimliği')),
                ('status', models.CharField(choices=[('pending', 'Onay bekliyor'), ('approved', 'Onaylandı'), ('applied', 'Uygulandı'), ('rejected', 'Reddedildi'), ('expired', 'Süresi doldu'), ('failed', 'Uygulama başarısız')], db_index=True, default='pending', max_length=20, verbose_name='Durum')),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Güven')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay zamanı')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Uygulama zamanı')),
                ('review_note', models.TextField(blank=True, verbose_name='Karar notu')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata')),
                ('call_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='aiservices.aicalllog', verbose_name='Çağrı kaydı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('created_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Öneri sahibi')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Yapay zekâ önerisi',
                'verbose_name_plural': 'Yapay zekâ önerileri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('provider', models.CharField(db_index=True, max_length=30, verbose_name='Sağlayıcı')),
                ('model', models.CharField(max_length=120, verbose_name='Model')),
                ('input_usd_per_million', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12, verbose_name='Girdi (USD / 1M belirteç)')),
                ('output_usd_per_million', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12, verbose_name='Çıktı (USD / 1M belirteç)')),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate, verbose_name='Geçerlilik başlangıcı')),
                ('source_note', models.CharField(blank=True, help_text='Fiyatın alındığı resmî sayfa ve tarih.', max_length=250, verbose_name='Kaynak notu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Etkin')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Sağlayıcı fiyatı',
                'verbose_name_plural': 'Sağlayıcı fiyatları',
                'ordering': ['provider', 'model', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='AIBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='Yıl')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='Ay')),
                ('limit_usd', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=12, verbose_name='Üst sınır (USD)')),
                ('spent_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=12, verbose_name='Harcanan (USD)')),
                ('warn_at_percent', models.PositiveSmallIntegerField(default=80, verbose_name='Uyarı eşiği (%)')),
                ('is_hard_limit', models.BooleanField(default=True, help_text='Açıkken sınır aşıldığında bulut çağrıları engellenir.', verbose_name='Kesin sınır')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Yapay zekâ bütçesi',
                'verbose_name_plural': 'Yapay zekâ bütçeleri',
                'ordering': ['-period_year', '-period_month'],
                'constraints': [models.UniqueConstraint(fields=('period_year', 'period_month'), name='uniq_ai_budget_period')],
            },
        ),
        migrations.AddIndex(
            model_name='aicalllog',
            index=models.Index(fields=['provider', '-occurred_at'], name='aicall_provider_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='aicalllog',
            index=models.Index(fields=['feature', '-occurred_at'], name='aicall_feature_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='aisuggestion',
            index=models.Index(fields=['status', '-created_at'], name='aisuggestion_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerpricing',
            constraint=models.UniqueConstraint(fields=('provider', 'model', 'effective_from'), name='uniq_pricing_period'),
        ),
    ]
