# Generated by Django 5.2.6 on 2026-08-18 05:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('business_date', models.DateField(db_index=True, unique=True, verbose_name='İş günü')),
                ('order_count', models.PositiveIntegerField(default=0, verbose_name='Adisyon')),
                ('guest_count', models.PositiveIntegerField(default=0, verbose_name='Misafir')),
                ('gross_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Brüt satış')),
                ('discounts', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='İndirim')),
                ('comps', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='İkram')),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Servis bedeli')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='KDV')),
                ('net_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Net satış')),
                ('cost_of_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Satış maliyeti')),
                ('food_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Yemek satışı')),
                ('beverage_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='İçecek satışı')),
                ('wine_bottle_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Şişe şarap satışı')),
                ('wine_glass_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Kadeh şarap satışı')),
                ('bottles_sold', models.PositiveIntegerField(default=0, verbose_name='Satılan şişe')),
                ('glasses_sold', models.PositiveIntegerField(default=0, verbose_name='Satılan kadeh')),
                ('void_count', models.PositiveIntegerField(default=0, verbose_name='İptal sayısı')),
                ('void_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='İptal tutarı')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='İade tutarı')),
                ('waste_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Fire maliyeti')),
                ('table_turns', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Masa devir hızı')),
                ('reservation_count', models.PositiveIntegerField(default=0, verbose_name='Rezervasyon')),
                ('no_show_count', models.PositiveIntegerField(default=0, verbose_name='Gelmeyen')),
                ('payment_breakdown', models.JSONField(blank=True, default=dict, verbose_name='Ödeme dağılımı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Günlük satış özeti',
                'verbose_name_plural': 'Günlük satış özetleri',
                'ordering': ['-business_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='Kod')),
                ('name_tr', models.CharField(max_length=200, verbose_name='Ad (TR)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Ad (EN)')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('category', models.CharField(choices=[('sales', 'Satış'), ('product', 'Ürün'), ('wine', 'Şarap'), ('inventory', 'Stok'), ('purchasing', 'Satın alma'), ('staff', 'Personel'), ('customer', 'Müşteri'), ('operations', 'Operasyon'), ('ai', 'Yapay zekâ'), ('finance', 'Mali')], max_length=20, verbose_name='Kategori')),
                ('allowed_roles', models.JSONField(blank=True, default=list, verbose_name='İzinli roller')),
                ('default_parameters', models.JSONField(blank=True, default=dict, verbose_name='Varsayılan parametreler')),
                ('supports_pdf', models.BooleanField(default=True, verbose_name='PDF desteği')),
                ('supports_excel', models.BooleanField(default=True, verbose_name='Excel desteği')),
                ('supports_csv', models.BooleanField(default=True, verbose_name='CSV desteği')),
                ('is_experimental', models.BooleanField(default=False, help_text="Arayüzde 'Deneysel' rozetiyle gösterilir.", verbose_name='Deneysel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Etkin')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Sıra')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Rapor tanımı',
                'verbose_name_plural': 'Rapor tanımları',
                'ordering': ['category', 'sort_order', 'name_tr'],
                'permissions': [('can_export_report', 'Rapor dışa aktarabilir'), ('can_view_financial_report', 'Mali raporları görebilir'), ('can_view_staff_report', 'Personel raporlarını görebilir')],
            },
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parametreler')),
                ('output_format', models.CharField(choices=[('html', 'Ekran'), ('pdf', 'PDF'), ('xlsx', 'Excel'), ('csv', 'CSV')], default='html', max_length=10, verbose_name='Biçim')),
                ('status', models.CharField(choices=[('running', 'Çalışıyor'), ('success', 'Tamamlandı'), ('failed', 'Başarısız')], default='running', max_length=20, verbose_name='Durum')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='Satır sayısı')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Süre (ms)')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Dosya yolu')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='reporting.reportdefinition', verbose_name='Rapor')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_runs', to=settings.AUTH_USER_MODEL, verbose_name='Çalıştıran')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Rapor koşumu',
                'verbose_name_plural': 'Rapor koşumları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('target_date', models.DateField(db_index=True, verbose_name='Hedef tarih')),
                ('method', models.CharField(choices=[('moving_average', 'Hareketli ortalama'), ('weekday_seasonal', 'Haftanın günü mevsimselliği'), ('ai_assisted', 'Yapay zekâ destekli')], default='weekday_seasonal', max_length=30, verbose_name='Yöntem')),
                ('predicted_covers', models.PositiveIntegerField(default=0, verbose_name='Tahmini misafir')),
                ('predicted_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Tahmini satış')),
                ('confidence_low', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Alt sınır')),
                ('confidence_high', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Üst sınır')),
                ('sample_days', models.PositiveSmallIntegerField(default=0, verbose_name='Örneklem (gün)')),
                ('actual_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Gerçekleşen satış')),
                ('ai_commentary', models.TextField(blank=True, verbose_name='Yapay zekâ yorumu')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Üretim zamanı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Satış tahmini',
                'verbose_name_plural': 'Satış tahminleri',
                'ordering': ['-target_date'],
                'constraints': [models.UniqueConstraint(fields=('target_date', 'method'), name='uniq_forecast_date_method')],
            },
        ),
    ]
