# Generated by Django 5.2.6 on 2026-08-18 05:38

import apps.core.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('key', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='Anahtar')),
                ('category', models.CharField(choices=[('general', 'Genel'), ('ai', 'Yapay zekâ'), ('payment', 'Ödeme'), ('backup', 'Yedekleme'), ('privacy', 'Gizlilik'), ('printing', 'Yazdırma'), ('devstudio', 'Geliştirici stüdyosu')], default='general', max_length=20, verbose_name='Kategori')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='Etiket')),
                ('help_text', models.TextField(blank=True, verbose_name='Açıklama')),
                ('value', models.JSONField(blank=True, default=dict, verbose_name='Değer')),
                ('secret_value', apps.core.fields.EncryptedTextField(blank=True, default='', verbose_name='Gizli değer')),
                ('is_secret', models.BooleanField(default=False, verbose_name='Gizli')),
                ('is_experimental', models.BooleanField(default=False, help_text="Arayüzde 'Deneysel' rozetiyle gösterilir.", verbose_name='Deneysel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Uygulama ayarı',
                'verbose_name_plural': 'Uygulama ayarları',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('ready', 'Hazır'), ('experimental', 'Deneysel'), ('planned', 'Planlandı'), ('disabled', 'Devre dışı')], default='planned', max_length=20, verbose_name='Durum')),
                ('module', models.CharField(blank=True, max_length=80, verbose_name='Modül')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Özellik bayrağı',
                'verbose_name_plural': 'Özellik bayrakları',
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Zaman')),
                ('actor_label', models.CharField(blank=True, help_text='Kullanıcı silinse bile iz kalması için kopyalanan kullanıcı adı.', max_length=150, verbose_name='Kullanıcı etiketi')),
                ('action', models.CharField(choices=[('create', 'Oluşturma'), ('update', 'Güncelleme'), ('delete', 'Silme'), ('view', 'Görüntüleme'), ('login', 'Giriş'), ('login_failed', 'Başarısız giriş'), ('logout', 'Çıkış'), ('permission_denied', 'Yetki reddi'), ('export', 'Dışa aktarım'), ('import', 'İçe aktarım'), ('backup', 'Yedekleme'), ('restore', 'Geri yükleme'), ('payment', 'Ödeme'), ('refund', 'İade'), ('void', 'İptal'), ('discount', 'İndirim'), ('stock_adjust', 'Stok düzeltme'), ('waste', 'Fire kaydı'), ('ai_request', 'Yapay zekâ isteği'), ('ai_apply', 'Yapay zekâ önerisi uygulama'), ('devstudio', 'Geliştirici stüdyosu işlemi'), ('settings', 'Ayar değişikliği'), ('consent', 'Rıza kaydı'), ('data_erasure', 'Veri silme talebi')], db_index=True, max_length=32, verbose_name='İşlem')),
                ('severity', models.CharField(choices=[('info', 'Bilgi'), ('notice', 'Dikkat'), ('warning', 'Uyarı'), ('critical', 'Kritik')], default='info', max_length=16, verbose_name='Önem')),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Nesne türü')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Nesne kimliği')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Nesne özeti')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Değişiklikler')),
                ('message', models.TextField(blank=True, verbose_name='Açıklama')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP adresi')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='İstemci')),
                ('success', models.BooleanField(default=True, verbose_name='Başarılı')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Denetim kaydı',
                'verbose_name_plural': 'Denetim kayıtları',
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['action', '-timestamp'], name='audit_action_ts_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_object_idx'), models.Index(fields=['actor', '-timestamp'], name='audit_actor_ts_idx')],
            },
        ),
    ]
