# Generated by Django 5.2.16 on 2026-08-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='integrity_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name="Bütünlük hash'i"),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='prev_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Önceki hash'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='İmza'),
        ),
    ]
