# Generated by Django 5.2.16 on 2026-08-18 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalRulePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('jurisdiction', models.CharField(choices=[('TR', 'Türkiye'), ('EU', 'AB/AEA')], db_index=True, max_length=8, verbose_name='Hukuk bölgesi')),
                ('regulation_code', models.CharField(db_index=True, max_length=30, verbose_name='Mevzuat kodu')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Sürüm')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('active', 'Yürürlükte'), ('retired', 'Emekli')], db_index=True, default='draft', max_length=10, verbose_name='Durum')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='Checksum')),
                ('signature', models.CharField(blank=True, max_length=64, verbose_name='İmza')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay zamanı')),
                ('release_note', models.CharField(blank=True, max_length=255, verbose_name='Sürüm notu')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_rulepacks', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Hukuki kural paketi',
                'verbose_name_plural': 'Hukuki kural paketleri',
                'ordering': ['jurisdiction', 'regulation_code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='LegalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('jurisdiction', models.CharField(choices=[('TR', 'Türkiye'), ('EU', 'AB/AEA')], db_index=True, max_length=8, verbose_name='Hukuk bölgesi')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('url', models.URLField(max_length=500, verbose_name='Resmî kaynak URL')),
                ('authority', models.CharField(max_length=120, verbose_name='Otorite')),
                ('article', models.CharField(blank=True, max_length=120, verbose_name='Madde/karar')),
                ('retrieved_on', models.DateField(blank=True, help_text='Kaynağın son doğrulandığı tarih; boşsa güncellik doğrulanmamıştır.', null=True, verbose_name='Erişim tarihi')),
                ('content_hash', models.CharField(blank=True, help_text='Kaynak metnin SHA-256 özeti; boşsa metin henüz arşivlenmemiştir.', max_length=64, verbose_name="İçerik hash'i")),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Not')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Hukuki kaynak',
                'verbose_name_plural': 'Hukuki kaynaklar',
                'ordering': ['jurisdiction', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LegalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('rule_code', models.CharField(db_index=True, max_length=60, verbose_name='Kural kodu')),
                ('title_tr', models.CharField(max_length=255, verbose_name='Başlık (TR)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Başlık (EN)')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('article', models.CharField(blank=True, max_length=120, verbose_name='Madde')),
                ('severity', models.CharField(choices=[('info', 'Bilgi'), ('medium', 'Orta'), ('high', 'Yüksek'), ('critical', 'Kritik')], default='high', max_length=10, verbose_name='Önem')),
                ('deadline_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Süre değeri')),
                ('deadline_unit', models.CharField(blank=True, choices=[('hours', 'Saat'), ('days', 'Takvim günü'), ('business_days', 'İş günü'), ('months', 'Ay')], max_length=16, verbose_name='Süre birimi')),
                ('requires_human_review', models.BooleanField(default=True, verbose_name='İnsan incelemesi gerekli')),
                ('evidence_requirements', models.JSONField(blank=True, default=list, verbose_name='Kanıt gereksinimleri')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='compliance.legalrulepack', verbose_name='Paket')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='compliance.legalsource', verbose_name='Resmî kaynak')),
            ],
            options={
                'verbose_name': 'Hukuki kural',
                'verbose_name_plural': 'Hukuki kurallar',
                'ordering': ['pack', 'rule_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='legalrulepack',
            constraint=models.UniqueConstraint(fields=('jurisdiction', 'regulation_code', 'version'), name='uniq_rulepack_version'),
        ),
        migrations.AddConstraint(
            model_name='legalrule',
            constraint=models.UniqueConstraint(fields=('pack', 'rule_code'), name='uniq_rule_per_pack'),
        ),
    ]
