# Generated by Django 5.2.6 on 2026-08-18 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='Kod')),
                ('title_tr', models.CharField(max_length=200, verbose_name='Başlık (TR)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Başlık (EN)')),
                ('summary_tr', models.TextField(blank=True, verbose_name='Özet (TR)')),
                ('summary_en', models.TextField(blank=True, verbose_name='Özet (EN)')),
                ('target_roles', models.JSONField(blank=True, default=list, verbose_name='Hedef roller')),
                ('level', models.CharField(choices=[('basic', 'Temel'), ('intermediate', 'Orta'), ('advanced', 'İleri')], default='basic', max_length=20, verbose_name='Seviye')),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=15, verbose_name='Tahmini süre (dk)')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Sıra')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Zorunlu')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında')),
                ('icon', models.CharField(blank=True, default='📘', max_length=40, verbose_name='Simge')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Eğitim modülü',
                'verbose_name_plural': 'Eğitim modülleri',
                'ordering': ['sort_order', 'title_tr'],
            },
        ),
        migrations.CreateModel(
            name='TrainingLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.SlugField(max_length=60, verbose_name='Kod')),
                ('title_tr', models.CharField(max_length=200, verbose_name='Başlık (TR)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Başlık (EN)')),
                ('content_tr', models.TextField(verbose_name='İçerik (TR)')),
                ('content_en', models.TextField(blank=True, verbose_name='İçerik (EN)')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Sıra')),
                ('related_url_name', models.CharField(blank=True, max_length=100, verbose_name='İlgili ekran')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='training.trainingmodule', verbose_name='Modül')),
            ],
            options={
                'verbose_name': 'Eğitim dersi',
                'verbose_name_plural': 'Eğitim dersleri',
                'ordering': ['module__sort_order', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='training.traininglesson', verbose_name='Ders')),
            ],
            options={
                'verbose_name': 'Ders ilerlemesi',
                'verbose_name_plural': 'Ders ilerlemeleri',
                'constraints': [models.UniqueConstraint(fields=('user', 'lesson'), name='uniq_user_lesson_progress')],
            },
        ),
        migrations.AddConstraint(
            model_name='traininglesson',
            constraint=models.UniqueConstraint(fields=('module', 'code'), name='uniq_module_lesson_code'),
        ),
    ]
