# Generated by Django 5.2.16 on 2026-08-18 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturma')),
                ('actor_label', models.CharField(blank=True, max_length=150, verbose_name='Aktör')),
                ('feature', models.CharField(db_index=True, max_length=30, verbose_name='AI işlevi')),
                ('action', models.CharField(default='TRANSFER', max_length=30, verbose_name='Eylem')),
                ('data_class', models.CharField(choices=[('public', 'Açık'), ('internal', 'Kurum içi'), ('confidential', 'Gizli'), ('restricted', 'Kısıtlı'), ('unknown', 'Bilinmiyor')], max_length=16, verbose_name='Veri sınıfı')),
                ('personal_class', models.CharField(choices=[('non_personal', 'Kişisel değil'), ('personal', 'Kişisel'), ('sensitive', 'Özel nitelikli'), ('unknown', 'Bilinmiyor')], max_length=16, verbose_name='Kişisel veri sınıfı')),
                ('decision', models.CharField(choices=[('allow', 'İzin'), ('allow_with_limits', 'Sınırlı izin'), ('local_only', 'Yalnızca yerel'), ('require_human_review', 'İnsan incelemesi gerekli'), ('deny', 'Red')], max_length=32, verbose_name='Karar')),
                ('applied_rule_ids', models.JSONField(blank=True, default=list, verbose_name='Uygulanan kurallar')),
                ('enforced_limits', models.JSONField(blank=True, default=dict, verbose_name='Uygulanan sınırlar')),
                ('provider', models.CharField(blank=True, max_length=40, verbose_name='Sağlayıcı')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='Model')),
                ('outcome', models.CharField(blank=True, max_length=20, verbose_name='Sonuç')),
                ('prev_hash', models.CharField(blank=True, max_length=64, verbose_name='Önceki hash')),
                ('integrity_hash', models.CharField(max_length=64, unique=True, verbose_name="Bütünlük hash'i")),
                ('signature', models.CharField(max_length=64, verbose_name='İmza')),
            ],
            options={
                'verbose_name': 'Haklar makbuzu',
                'verbose_name_plural': 'Haklar makbuzları',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HSPPolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('feature', models.CharField(db_index=True, help_text="aiservices.AIFeature kodu; '*' tüm işlevler demektir.", max_length=30, verbose_name='AI işlevi')),
                ('decision', models.CharField(choices=[('allow', 'İzin'), ('allow_with_limits', 'Sınırlı izin'), ('local_only', 'Yalnızca yerel'), ('require_human_review', 'İnsan incelemesi gerekli'), ('deny', 'Red')], default='local_only', max_length=32, verbose_name='Karar')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Gerekçe')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Sürüm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay zamanı')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_hsp_rules', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'HSP politika kuralı',
                'verbose_name_plural': 'HSP politika kuralları',
                'ordering': ['feature', '-version'],
            },
        ),
    ]
