# Generated by Django 5.2.16 on 2026-08-18 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('agent_name', models.CharField(db_index=True, max_length=100, verbose_name='Ajan')),
                ('allowed_actions', models.JSONField(default=list, help_text='Eylem kodları listesi; boş liste hiçbir eyleme izin vermez.', verbose_name='İzinli eylemler')),
                ('max_amount_eur', models.DecimalField(blank=True, decimal_places=2, help_text='Boş = parasal yetki yok. Sınırsız yetki tanımlanamaz.', max_digits=12, null=True, verbose_name='Parasal üst sınır (EUR)')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Son geçerlilik')),
                ('revoked', models.BooleanField(default=False, verbose_name='İptal edildi')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='İptal zamanı')),
                ('issued_by_label', models.CharField(blank=True, max_length=150, verbose_name='Veren')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='hsp.authorityenvelope', verbose_name='Üst zarf')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Ajan yetki zarfı',
                'verbose_name_plural': 'Ajan yetki zarfları',
                'ordering': ['agent_name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HSPReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('feature', models.CharField(db_index=True, max_length=30, verbose_name='AI işlevi')),
                ('requested_by_label', models.CharField(blank=True, max_length=150, verbose_name='Talep eden')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], db_index=True, default='pending', max_length=16, verbose_name='Durum')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Gerekçe')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Karar zamanı')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Onay bu andan sonra geçersizdir; yeni inceleme gerekir.', null=True, verbose_name='Onay geçerlilik sonu')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_hsp_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Karar veren')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'HSP inceleme talebi',
                'verbose_name_plural': 'HSP inceleme talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
