# Generated by Django 5.2.16 on 2026-08-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsp', '0002_authorityenvelope_hspreviewrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorityEnvelope',
        ),
    ]
