# Generated by Django 5.2.6 on 2026-08-18 05:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('sequence', models.PositiveSmallIntegerField(default=1, verbose_name='Sıra')),
                ('action_type', models.CharField(choices=[('file_create', 'Dosya oluştur'), ('file_edit', 'Dosya düzenle'), ('file_delete', 'Dosya sil'), ('run_command', 'Komut çalıştır'), ('run_tests', 'Test çalıştır'), ('run_lint', 'Kod kalitesi denetimi'), ('git_branch', 'Dal oluştur'), ('git_commit', 'Commit oluştur'), ('git_revert', 'Değişikliği geri al')], max_length=20, verbose_name='Eylem türü')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Açıklama')),
                ('target_path', models.CharField(blank=True, max_length=500, verbose_name='Hedef dosya')),
                ('command', models.TextField(blank=True, verbose_name='Komut')),
                ('proposed_content', models.TextField(blank=True, verbose_name='Önerilen içerik')),
                ('previous_content', models.TextField(blank=True, verbose_name='Önceki içerik')),
                ('diff_text', models.TextField(blank=True, verbose_name='Fark (diff)')),
                ('policy_decision', models.CharField(blank=True, max_length=20, verbose_name='Politika kararı')),
                ('policy_reason', models.TextField(blank=True, verbose_name='Politika gerekçesi')),
                ('policy_rule', models.CharField(blank=True, max_length=60, verbose_name='Eşleşen kural')),
                ('status', models.CharField(choices=[('proposed', 'Önerildi'), ('blocked', 'Politika engelledi'), ('awaiting', 'Onay bekliyor'), ('approved', 'Onaylandı'), ('executed', 'Uygulandı'), ('rejected', 'Reddedildi'), ('failed', 'Başarısız'), ('reverted', 'Geri alındı')], db_index=True, default='proposed', max_length=20, verbose_name='Durum')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Uygulama zamanı')),
                ('exit_code', models.IntegerField(blank=True, null=True, verbose_name='Çıkış kodu')),
                ('output', models.TextField(blank=True, verbose_name='Çıktı')),
                ('error_output', models.TextField(blank=True, verbose_name='Hata çıktısı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_actions_executed', to=settings.AUTH_USER_MODEL, verbose_name='Uygulayan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Geliştirme eylemi',
                'verbose_name_plural': 'Geliştirme eylemleri',
                'ordering': ['session', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='DevSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('title', models.CharField(max_length=250, verbose_name='Başlık')),
                ('request_text', models.TextField(help_text='Kullanıcının doğal dilde tarifi.', verbose_name='İstek')),
                ('plan_text', models.TextField(blank=True, verbose_name='Plan')),
                ('status', models.CharField(choices=[('planning', 'Plan hazırlanıyor'), ('proposed', 'Öneri hazır'), ('approved', 'Onaylandı'), ('applied', 'Uygulandı'), ('testing', 'Test ediliyor'), ('tests_passed', 'Testler geçti'), ('tests_failed', 'Testler başarısız'), ('merged', 'Ana dala birleştirildi'), ('reverted', 'Geri alındı'), ('rejected', 'Reddedildi'), ('failed', 'Başarısız')], db_index=True, default='planning', max_length=20, verbose_name='Durum')),
                ('provider', models.CharField(blank=True, max_length=30, verbose_name='Sağlayıcı')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='Model')),
                ('base_branch', models.CharField(blank=True, max_length=120, verbose_name='Kaynak dal')),
                ('work_branch', models.CharField(blank=True, max_length=120, verbose_name='Çalışma dalı')),
                ('commit_sha', models.CharField(blank=True, max_length=40, verbose_name='Commit')),
                ('rollback_sha', models.CharField(blank=True, max_length=40, verbose_name='Geri alma noktası')),
                ('tests_run', models.BooleanField(default=False, verbose_name='Test çalıştırıldı')),
                ('tests_passed', models.BooleanField(default=False, verbose_name='Testler geçti')),
                ('test_output', models.TextField(blank=True, verbose_name='Test çıktısı')),
                ('lint_passed', models.BooleanField(default=False, verbose_name='Kod kalitesi geçti')),
                ('lint_output', models.TextField(blank=True, verbose_name='Kalite çıktısı')),
                ('total_prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='İstem belirteci')),
                ('total_completion_tokens', models.PositiveIntegerField(default=0, verbose_name='Yanıt belirteci')),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Tahmini maliyet (USD)')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay zamanı')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_sessions_approved', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dev_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Talep eden')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Geliştirme oturumu',
                'verbose_name_plural': 'Geliştirme oturumları',
                'ordering': ['-created_at'],
                'permissions': [('can_open_devstudio', 'AI Development Studio açabilir'), ('can_apply_dev_change', 'Kod değişikliği uygulayabilir'), ('can_merge_dev_branch', 'Çalışma dalını birleştirebilir'), ('can_run_dev_commands', 'Denetlenmiş komut çalıştırabilir')],
            },
        ),
        migrations.CreateModel(
            name='DevAuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Zaman')),
                ('event', models.CharField(db_index=True, max_length=80, verbose_name='Olay')),
                ('detail', models.TextField(blank=True, verbose_name='Ayrıntı')),
                ('is_security_relevant', models.BooleanField(default=False, verbose_name='Güvenlikle ilgili')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='devstudio.devaction', verbose_name='Eylem')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devstudio_audit', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='devstudio.devsession', verbose_name='Oturum')),
            ],
            options={
                'verbose_name': 'Stüdyo denetim kaydı',
                'verbose_name_plural': 'Stüdyo denetim kayıtları',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='devaction',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='devstudio.devsession', verbose_name='Oturum'),
        ),
    ]
