# Generated by Django 5.2.6 on 2026-08-18 05:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devstudio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('category', models.CharField(choices=[('ai_quality', 'Yapay zekâ yanıt kalitesi'), ('ai_cost', 'Yapay zekâ maliyeti'), ('ai_reliability', 'Sağlayıcı güvenilirliği'), ('performance', 'Başarım'), ('error_pattern', 'Tekrar eden hata'), ('ux', 'Kullanıcı deneyimi'), ('data_quality', 'Veri kalitesi'), ('report_accuracy', 'Rapor doğruluğu'), ('feature_idea', 'Yeni özellik önerisi'), ('security', 'Güvenlik')], db_index=True, max_length=30, verbose_name='Kategori')),
                ('severity', models.CharField(choices=[('info', 'Bilgi'), ('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('critical', 'Kritik')], db_index=True, default='low', max_length=20, verbose_name='Önem')),
                ('status', models.CharField(choices=[('open', 'Açık'), ('acknowledged', 'Görüldü'), ('planned', 'Planlandı'), ('in_progress', 'Üzerinde çalışılıyor'), ('resolved', 'Çözüldü'), ('dismissed', 'Kapatıldı')], db_index=True, default='open', max_length=20, verbose_name='Durum')),
                ('title', models.CharField(max_length=250, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('evidence', models.JSONField(blank=True, default=dict, verbose_name='Kanıt')),
                ('recommendation', models.TextField(blank=True, verbose_name='Öneri')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, verbose_name='Parmak izi')),
                ('occurrence_count', models.PositiveIntegerField(default=1, verbose_name='Tekrar sayısı')),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='İlk görülme')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Son görülme')),
                ('review_note', models.TextField(blank=True, verbose_name='İnceleme notu')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('dev_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caio_findings', to='devstudio.devsession', verbose_name='Geliştirme oturumu')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caio_findings_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='İnceleyen')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'CAIO bulgusu',
                'verbose_name_plural': 'CAIO bulguları',
                'ordering': ['-severity', '-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='ImprovementTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('title', models.CharField(max_length=250, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Düşük'), (2, 'Normal'), (3, 'Yüksek'), (4, 'Acil')], default=2, verbose_name='Öncelik')),
                ('status', models.CharField(choices=[('backlog', 'Bekleyen'), ('approved', 'Onaylandı'), ('in_progress', 'Devam ediyor'), ('done', 'Tamamlandı'), ('cancelled', 'İptal')], db_index=True, default='backlog', max_length=20, verbose_name='Durum')),
                ('target_release', models.CharField(blank=True, max_length=20, verbose_name='Hedef sürüm')),
                ('estimated_effort_hours', models.PositiveSmallIntegerField(default=0, verbose_name='Tahmini efor (saat)')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caio_tasks_approved', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('findings', models.ManyToManyField(blank=True, related_name='tasks', to='caio.finding', verbose_name='İlgili bulgular')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Geliştirme görevi',
                'verbose_name_plural': 'Geliştirme görevleri',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('trigger', models.CharField(choices=[('manual', 'El ile'), ('scheduled', 'Zamanlanmış'), ('post_day_end', 'Gün sonu sonrası')], default='manual', max_length=20, verbose_name='Tetikleyici')),
                ('status', models.CharField(choices=[('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='running', max_length=20, verbose_name='Durum')),
                ('period_start', models.DateTimeField(verbose_name='Dönem başı')),
                ('period_end', models.DateTimeField(verbose_name='Dönem sonu')),
                ('ai_calls_examined', models.PositiveIntegerField(default=0, verbose_name='İncelenen çağrı')),
                ('failed_calls', models.PositiveIntegerField(default=0, verbose_name='Başarısız çağrı')),
                ('fallback_calls', models.PositiveIntegerField(default=0, verbose_name='Yedeğe düşen çağrı')),
                ('low_rated_responses', models.PositiveIntegerField(default=0, verbose_name='Düşük puanlı yanıt')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='Toplam belirteç')),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12, verbose_name='Toplam maliyet (USD)')),
                ('average_latency_ms', models.PositiveIntegerField(default=0, verbose_name='Ortalama gecikme (ms)')),
                ('findings_count', models.PositiveIntegerField(default=0, verbose_name='Bulgu sayısı')),
                ('summary', models.TextField(blank=True, verbose_name='Özet')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caio_runs', to=settings.AUTH_USER_MODEL, verbose_name='Başlatan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'CAIO gözlem koşumu',
                'verbose_name_plural': 'CAIO gözlem koşumları',
                'ordering': ['-created_at'],
                'permissions': [('can_run_caio', 'CAIO gözlemi başlatabilir'), ('can_review_caio_findings', 'CAIO bulgularını inceleyebilir')],
            },
        ),
        migrations.AddField(
            model_name='finding',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='caio.observationrun', verbose_name='Koşum'),
        ),
        migrations.CreateModel(
            name='ExportValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('report_code', models.CharField(max_length=80, verbose_name='Rapor kodu')),
                ('output_format', models.CharField(max_length=10, verbose_name='Biçim')),
                ('result', models.CharField(choices=[('passed', 'Geçti'), ('failed', 'Başarısız'), ('skipped', 'Atlandı')], max_length=20, verbose_name='Sonuç')),
                ('checked_rows', models.PositiveIntegerField(default=0, verbose_name='Denetlenen satır')),
                ('mismatches', models.JSONField(blank=True, default=list, verbose_name='Uyuşmazlıklar')),
                ('turkish_characters_ok', models.BooleanField(default=True, verbose_name='Türkçe karakterler doğru')),
                ('totals_ok', models.BooleanField(default=True, verbose_name='Toplamlar doğru')),
                ('detail', models.TextField(blank=True, verbose_name='Ayrıntı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_validations', to='caio.observationrun', verbose_name='Koşum')),
            ],
            options={
                'verbose_name': 'Dışa aktarım doğrulaması',
                'verbose_name_plural': 'Dışa aktarım doğrulamaları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseNoteDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('version', models.CharField(max_length=20, verbose_name='Sürüm')),
                ('period_start', models.DateField(verbose_name='Dönem başı')),
                ('period_end', models.DateField(verbose_name='Dönem sonu')),
                ('content_tr', models.TextField(verbose_name='İçerik (TR)')),
                ('content_en', models.TextField(blank=True, verbose_name='İçerik (EN)')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('reviewed', 'İncelendi'), ('published', 'Yayınlandı')], default='draft', max_length=20, verbose_name='Durum')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_notes_approved', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Sürüm notu taslağı',
                'verbose_name_plural': 'Sürüm notu taslakları',
                'ordering': ['-period_end'],
            },
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.UniqueConstraint(fields=('fingerprint',), name='uniq_finding_fingerprint'),
        ),
    ]
