# Generated by Django 5.2.6 on 2026-08-18 05:38

import apps.core.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Silindi')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme zamanı')),
                ('employee_code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Personel kodu')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('job_title', models.CharField(max_length=120, verbose_name='Görev')),
                ('department', models.CharField(choices=[('service', 'Servis'), ('kitchen', 'Mutfak'), ('bar', 'Bar'), ('cellar', 'Kav'), ('management', 'Yönetim'), ('back_office', 'Arka ofis')], default='service', max_length=40, verbose_name='Departman')),
                ('employment_type', models.CharField(choices=[('full_time', 'Tam zamanlı'), ('part_time', 'Yarı zamanlı'), ('seasonal', 'Sezonluk'), ('intern', 'Stajyer'), ('contractor', 'Sözleşmeli')], default='full_time', max_length=20, verbose_name='Çalışma şekli')),
                ('status', models.CharField(choices=[('active', 'Çalışıyor'), ('on_leave', 'İzinde'), ('suspended', 'Askıda'), ('terminated', 'Ayrıldı')], db_index=True, default='active', max_length=20, verbose_name='Durum')),
                ('national_id', apps.core.fields.EncryptedCharField(blank=True, default='', verbose_name='Kimlik numarası')),
                ('phone', apps.core.fields.EncryptedCharField(blank=True, default='', verbose_name='Telefon')),
                ('email', apps.core.fields.EncryptedCharField(blank=True, default='', verbose_name='E-posta')),
                ('emergency_contact', apps.core.fields.EncryptedCharField(blank=True, default='', verbose_name='Acil durum iletişim')),
                ('address', apps.core.fields.EncryptedCharField(blank=True, default='', verbose_name='Adres')),
                ('iban', apps.core.fields.EncryptedCharField(blank=True, default='', verbose_name='IBAN')),
                ('hired_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='İşe giriş')),
                ('terminated_on', models.DateField(blank=True, null=True, verbose_name='Çıkış tarihi')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Saatlik ücret')),
                ('annual_leave_days', models.PositiveSmallIntegerField(default=14, verbose_name='Yıllık izin hakkı (gün)')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Silen')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Sistem kullanıcısı')),
            ],
            options={
                'verbose_name': 'Personel',
                'verbose_name_plural': 'Personel',
                'ordering': ['last_name', 'first_name'],
                'permissions': [('view_employee_sensitive', 'Personel hassas bilgilerini görebilir'), ('can_manage_payroll', 'Bordro bilgilerini yönetebilir')],
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('starts_at', models.TimeField(verbose_name='Başlangıç saati')),
                ('ends_at', models.TimeField(verbose_name='Bitiş saati')),
                ('break_minutes', models.PositiveSmallIntegerField(default=30, verbose_name='Mola (dk)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Etkin')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Vardiya şablonu',
                'verbose_name_plural': 'Vardiya şablonları',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('shift_date', models.DateField(db_index=True, verbose_name='Tarih')),
                ('starts_at', models.DateTimeField(verbose_name='Başlangıç')),
                ('ends_at', models.DateTimeField(verbose_name='Bitiş')),
                ('status', models.CharField(choices=[('planned', 'Planlandı'), ('published', 'Yayınlandı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal')], default='planned', max_length=20, verbose_name='Durum')),
                ('required_staff', models.PositiveSmallIntegerField(default=1, verbose_name='Gerekli personel')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='hr.shifttemplate', verbose_name='Şablon')),
            ],
            options={
                'verbose_name': 'Vardiya',
                'verbose_name_plural': 'Vardiyalar',
                'ordering': ['-shift_date', 'starts_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('started_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Başlangıç')),
                ('completed_on', models.DateField(blank=True, null=True, verbose_name='Tamamlanma')),
                ('result', models.CharField(choices=[('completed', 'Tamamlandı'), ('in_progress', 'Devam ediyor'), ('failed', 'Başarısız')], default='in_progress', max_length=20, verbose_name='Sonuç')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Puan')),
                ('certificate_number', models.CharField(blank=True, max_length=40, verbose_name='Sertifika no')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='hr.employee', verbose_name='Personel')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_records', to='training.trainingmodule', verbose_name='Eğitim modülü')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Eğitim kaydı',
                'verbose_name_plural': 'Eğitim kayıtları',
                'ordering': ['-started_on'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'module'), name='uniq_employee_training_module')],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('leave_type', models.CharField(choices=[('annual', 'Yıllık izin'), ('sick', 'Hastalık izni'), ('unpaid', 'Ücretsiz izin'), ('maternity', 'Doğum izni'), ('bereavement', 'Ölüm izni'), ('other', 'Diğer')], max_length=20, verbose_name='İzin türü')),
                ('start_date', models.DateField(verbose_name='Başlangıç')),
                ('end_date', models.DateField(verbose_name='Bitiş')),
                ('status', models.CharField(choices=[('pending', 'Onay bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal')], db_index=True, default='pending', max_length=20, verbose_name='Durum')),
                ('reason', models.TextField(blank=True, verbose_name='Gerekçe')),
                ('review_note', models.CharField(blank=True, max_length=250, verbose_name='Karar notu')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.employee', verbose_name='Personel')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Karar veren')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'İzin talebi',
                'verbose_name_plural': 'İzin talepleri',
                'ordering': ['-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='leave_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('period_start', models.DateField(verbose_name='Dönem başı')),
                ('period_end', models.DateField(verbose_name='Dönem sonu')),
                ('orders_served', models.PositiveIntegerField(default=0, verbose_name='Adisyon sayısı')),
                ('guests_served', models.PositiveIntegerField(default=0, verbose_name='Misafir sayısı')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Toplam satış')),
                ('average_check', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ortalama adisyon')),
                ('wine_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Şarap satışı')),
                ('wine_attach_rate', models.DecimalField(decimal_places=2, default=0, help_text='Şarap içeren adisyonların toplam adisyona oranı.', max_digits=5, verbose_name='Şarap ekleme oranı (%)')),
                ('void_count', models.PositiveIntegerField(default=0, verbose_name='İptal sayısı')),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Verilen indirim')),
                ('average_service_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Ortalama servis süresi (dk)')),
                ('manager_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Yönetici değerlendirmesi (1-5)')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Yönetici yorumu')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='hr.employee', verbose_name='Personel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Performans göstergesi',
                'verbose_name_plural': 'Performans göstergeleri',
                'ordering': ['-period_end'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'period_start', 'period_end'), name='uniq_employee_period')],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('role_code', models.CharField(blank=True, max_length=40, verbose_name='Görev rolü')),
                ('clock_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Giriş saati')),
                ('clock_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Çıkış saati')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='İptal')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Not')),
                ('assigned_tables', models.ManyToManyField(blank=True, related_name='shift_assignments', to='operations.diningtable', verbose_name='Atanan masalar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_assignments', to='hr.employee', verbose_name='Personel')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_assignments', to='operations.floorsection', verbose_name='Bölge')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hr.shift', verbose_name='Vardiya')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Vardiya ataması',
                'verbose_name_plural': 'Vardiya atamaları',
                'ordering': ['shift__shift_date'],
                'constraints': [models.UniqueConstraint(fields=('shift', 'employee'), name='uniq_shift_employee')],
            },
        ),
    ]
