# Generated by Django 5.2.6 on 2026-08-18 05:38

import apps.core.fields
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='Kullanıcı adı')),
                ('successful', models.BooleanField(default=False, verbose_name='Başarılı')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP adresi')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='İstemci')),
                ('method', models.CharField(choices=[('password', 'Parola'), ('pin', 'PIN')], default='password', max_length=20, verbose_name='Yöntem')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Zaman')),
            ],
            options={
                'verbose_name': 'Giriş denemesi',
                'verbose_name_plural': 'Giriş denemeleri',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('display_name', models.CharField(blank=True, help_text='Fişlerde ve ekranlarda gösterilecek ad.', max_length=150, verbose_name='Görünen ad')),
                ('primary_role', models.CharField(blank=True, choices=[('owner', 'İşletme Sahibi'), ('general_manager', 'Genel Müdür'), ('restaurant_manager', 'Restoran Müdürü'), ('head_sommelier', 'Baş Sommelier'), ('sommelier', 'Sommelier'), ('cellar_master', 'Kav ve Şarap Deposu Sorumlusu'), ('executive_chef', 'Executive Chef'), ('kitchen_staff', 'Mutfak Personeli'), ('waiter', 'Garson'), ('busser', 'Komi'), ('bartender', 'Barmen'), ('cashier', 'Kasiyer'), ('host', 'Rezervasyon Görevlisi'), ('purchasing', 'Satın Alma Sorumlusu'), ('warehouse', 'Depo Görevlisi'), ('accounting', 'Muhasebe'), ('hr', 'İnsan Kaynakları'), ('sysadmin', 'Sistem Yöneticisi'), ('auditor', 'Denetçi (Salt Okunur)')], db_index=True, max_length=40, verbose_name='Birincil rol')),
                ('phone', apps.core.fields.EncryptedCharField(blank=True, default='', verbose_name='Telefon')),
                ('preferred_language', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English')], default='tr', max_length=5, verbose_name='Tercih edilen dil')),
                ('pin_hash', models.CharField(blank=True, default='', max_length=255, verbose_name='PIN özeti')),
                ('pin_enabled', models.BooleanField(default=False, verbose_name='PIN girişi açık')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='Parola değiştirmeli')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Parola değişim zamanı')),
                ('failed_login_count', models.PositiveSmallIntegerField(default=0, verbose_name='Başarısız giriş')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Kilit bitişi')),
                ('discount_limit_percent', models.DecimalField(decimal_places=2, default=0, help_text='Bu oranın üzerindeki indirimler ikinci onay gerektirir.', max_digits=5, verbose_name='İndirim yetkisi (%)')),
                ('employee_code', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Personel kodu')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'permissions': [('can_manage_roles', 'Rol ve yetki yönetebilir'), ('can_view_audit_log', 'Denetim kaydını görüntüleyebilir'), ('can_use_devstudio', 'AI Development Studio kullanabilir'), ('can_approve_critical', 'Kritik işlemleri onaylayabilir')],
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RoleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Rol kodu')),
                ('name_tr', models.CharField(max_length=100, verbose_name='Ad (TR)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Ad (EN)')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('level', models.PositiveSmallIntegerField(default=5, verbose_name='Kademe')),
                ('is_system', models.BooleanField(default=True, help_text='Sistem rolleri arayüzden silinemez.', verbose_name='Sistem rolü')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group', verbose_name='Grup')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Rol profili',
                'verbose_name_plural': 'Rol profilleri',
                'ordering': ['level', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('action', models.CharField(choices=[('void_order', 'Sipariş iptali'), ('refund_payment', 'Ödeme iadesi'), ('discount_over_limit', 'Yetki sınırını aşan indirim'), ('comp_item', 'İkram (bedelsiz ürün)'), ('stock_adjust', 'Stok düzeltmesi'), ('waste_high_value', 'Yüksek değerli fire kaydı'), ('price_override', 'Fiyat değiştirme'), ('close_day', 'Gün sonu kapanışı'), ('restore_backup', 'Yedekten geri yükleme'), ('erase_customer_data', 'Müşteri verisi silme (KVKK)'), ('apply_ai_change', 'Yapay zekâ önerisini uygulama'), ('devstudio_merge', 'Geliştirici stüdyosu birleştirme')], db_index=True, max_length=50, verbose_name='İşlem')),
                ('status', models.CharField(choices=[('pending', 'Onay bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('expired', 'Süresi doldu'), ('applied', 'Uygulandı')], db_index=True, default='pending', max_length=20, verbose_name='Durum')),
                ('reason', models.TextField(blank=True, verbose_name='Gerekçe')),
                ('review_note', models.TextField(blank=True, verbose_name='Onay notu')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='İşlem verisi')),
                ('object_type', models.CharField(blank=True, max_length=100, verbose_name='Nesne türü')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='Nesne kimliği')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay zamanı')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Geçerlilik bitişi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='Talep eden')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_given', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Onay talebi',
                'verbose_name_plural': 'Onay talepleri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='approval_status_idx')],
            },
        ),
    ]
