# Generated by Django 5.2.6 on 2026-08-18 05:38

import apps.core.fields
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('cellar', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerVisitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('kind', models.CharField(choices=[('preference', 'Tercih'), ('complaint', 'Şikâyet'), ('compliment', 'Övgü'), ('incident', 'Olay'), ('general', 'Genel')], default='general', max_length=20, verbose_name='Tür')),
                ('note', models.TextField(verbose_name='Not')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Çözüldü')),
            ],
            options={
                'verbose_name': 'Ziyaret notu',
                'verbose_name_plural': 'Ziyaret notları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataErasureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('requested_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Talep tarihi')),
                ('status', models.CharField(choices=[('received', 'Alındı'), ('approved', 'Onaylandı'), ('completed', 'Tamamlandı'), ('rejected', 'Reddedildi')], default='received', max_length=20, verbose_name='Durum')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma')),
                ('rejection_reason', models.CharField(blank=True, max_length=250, verbose_name='Ret gerekçesi')),
                ('retained_records_note', models.TextField(blank=True, help_text='Yasal zorunluluk nedeniyle korunan kayıtların açıklaması.', verbose_name='Saklanan kayıtlar')),
            ],
            options={
                'verbose_name': 'Veri silme talebi',
                'verbose_name_plural': 'Veri silme talepleri',
                'ordering': ['-requested_on'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('card_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Kart numarası')),
                ('points_balance', models.IntegerField(default=0, verbose_name='Puan bakiyesi')),
                ('tier', models.CharField(blank=True, max_length=40, verbose_name='Kademe')),
                ('joined_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Katılım tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Etkin')),
            ],
            options={
                'verbose_name': 'Sadakat hesabı',
                'verbose_name_plural': 'Sadakat hesapları',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Ad')),
                ('points_per_currency', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=8, verbose_name='Birim harcama başına puan')),
                ('currency_per_point', models.DecimalField(decimal_places=4, default=Decimal('0.0100'), max_digits=8, verbose_name='Puan başına indirim tutarı')),
                ('minimum_redeem_points', models.PositiveIntegerField(default=100, verbose_name='Asgari kullanım puanı')),
                ('points_expire_days', models.PositiveSmallIntegerField(default=365, help_text='0 = süresiz.', verbose_name='Puan geçerliliği (gün)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Etkin')),
            ],
            options={
                'verbose_name': 'Sadakat programı',
                'verbose_name_plural': 'Sadakat programları',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('kind', models.CharField(choices=[('earn', 'Kazanım'), ('redeem', 'Kullanım'), ('adjust', 'Düzeltme'), ('expire', 'Süre dolumu'), ('bonus', 'Bonus')], max_length=20, verbose_name='Tür')),
                ('points', models.IntegerField(help_text='Kazanım pozitif, kullanım negatif.', verbose_name='Puan')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Zaman')),
                ('expires_on', models.DateField(blank=True, null=True, verbose_name='Geçerlilik')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Not')),
            ],
            options={
                'verbose_name': 'Sadakat hareketi',
                'verbose_name_plural': 'Sadakat hareketleri',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('channel', models.CharField(choices=[('in_house', 'İşletme içi (personel bilgilendirmesi)'), ('email', 'E-posta'), ('sms', 'SMS')], default='in_house', max_length=20, verbose_name='Kanal')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('scheduled', 'Planlandı'), ('running', 'Yürürlükte'), ('ended', 'Sona erdi'), ('cancelled', 'İptal')], default='draft', max_length=20, verbose_name='Durum')),
                ('starts_on', models.DateField(blank=True, null=True, verbose_name='Başlangıç')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='Bitiş')),
                ('target_segments', models.JSONField(blank=True, default=list, verbose_name='Hedef segmentler')),
                ('requires_consent', models.BooleanField(default=True, verbose_name='Rıza gerektirir')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('price_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='catalog.pricerule', verbose_name='Bağlı fiyat kuralı')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Kampanya',
                'verbose_name_plural': 'Kampanyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('purpose', models.CharField(choices=[('service', 'Hizmet sunumu (rezervasyon, sipariş)'), ('marketing_email', 'E-posta ile pazarlama'), ('marketing_sms', 'SMS ile pazarlama'), ('profiling', 'Tercih analizi / kişiselleştirme'), ('ai_processing', 'Yapay zekâ ile analiz'), ('photo', 'Fotoğraf / görüntü kullanımı')], db_index=True, max_length=30, verbose_name='Amaç')),
                ('is_granted', models.BooleanField(default=False, verbose_name='Rıza verildi')),
                ('granted_at', models.DateTimeField(blank=True, null=True, verbose_name='Rıza zamanı')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='Geri çekilme zamanı')),
                ('collection_method', models.CharField(blank=True, max_length=100, verbose_name='Alınma yöntemi')),
                ('policy_version', models.CharField(blank=True, max_length=20, verbose_name='Aydınlatma metni sürümü')),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='Not')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_consents', to=settings.AUTH_USER_MODEL, verbose_name='Alan personel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Rıza kaydı',
                'verbose_name_plural': 'Rıza kayıtları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Silindi')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme zamanı')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Müşteri kodu')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Soyad')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Firma')),
                ('phone', apps.core.fields.EncryptedCharField(blank=True, default='', verbose_name='Telefon')),
                ('phone_index', models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Telefon arama özeti')),
                ('email', apps.core.fields.EncryptedCharField(blank=True, default='', verbose_name='E-posta')),
                ('email_index', models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='E-posta arama özeti')),
                ('birth_date', apps.core.fields.EncryptedCharField(blank=True, default='', help_text='GG.AA.YYYY biçiminde.', verbose_name='Doğum tarihi')),
                ('birth_day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Doğum günü')),
                ('birth_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Doğum ayı')),
                ('segment', models.CharField(choices=[('new', 'Yeni'), ('regular', 'Düzenli'), ('vip', 'VIP'), ('corporate', 'Kurumsal'), ('inactive', 'Pasif')], db_index=True, default='new', max_length=20, verbose_name='Segment')),
                ('preferred_language', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English')], default='tr', max_length=5, verbose_name='Tercih edilen dil')),
                ('dietary_notes', models.TextField(blank=True, verbose_name='Beslenme tercihleri')),
                ('allergy_notes', models.TextField(blank=True, help_text='Misafirin beyanına dayanır. Tıbbi tavsiye değildir; mutfak her durumda kendi kontrolünü yapmalıdır.', verbose_name='Alerji notları')),
                ('notes', models.TextField(blank=True, verbose_name='Genel notlar')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='Kara liste')),
                ('blacklist_reason', models.CharField(blank=True, max_length=250, verbose_name='Kara liste gerekçesi')),
                ('first_visit_on', models.DateField(blank=True, null=True, verbose_name='İlk ziyaret')),
                ('last_visit_on', models.DateField(blank=True, db_index=True, null=True, verbose_name='Son ziyaret')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Silen')),
                ('favorite_menu_items', models.ManyToManyField(blank=True, related_name='fans', to='catalog.menuitem', verbose_name='Favori yemekler')),
                ('favorite_wines', models.ManyToManyField(blank=True, related_name='fans', to='cellar.wine', verbose_name='Favori şaraplar')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
                'ordering': ['last_name', 'first_name'],
                'permissions': [('can_export_customer_data', 'Müşteri verisini dışa aktarabilir'), ('can_erase_customer_data', 'Müşteri verisini silebilir (KVKK)'), ('view_customer_contact', 'Müşteri iletişim bilgilerini görebilir')],
            },
        ),
    ]
