# Generated by Django 5.2.6 on 2026-08-18 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('cellar', '0002_initial'),
        ('crm', '0001_initial'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pouringrecord',
            name='order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pours', to='operations.orderline', verbose_name='Sipariş satırı'),
        ),
        migrations.AddField(
            model_name='pouringrecord',
            name='poured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pours', to=settings.AUTH_USER_MODEL, verbose_name='Servis eden'),
        ),
        migrations.AddField(
            model_name='pouringrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='privatecellarbottle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='privatecellarbottle',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='privatecellarclient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='privatecellarclient',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='private_cellar', to='crm.customer', verbose_name='Müşteri'),
        ),
        migrations.AddField(
            model_name='privatecellarclient',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='privatecellarbottle',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottles', to='cellar.privatecellarclient', verbose_name='Özel kav müşterisi'),
        ),
        migrations.AddField(
            model_name='storagereading',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='storagereading',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_readings', to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden'),
        ),
        migrations.AddField(
            model_name='storagereading',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='tastingevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='tastingevent',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_tastings', to=settings.AUTH_USER_MODEL, verbose_name='Sunan'),
        ),
        migrations.AddField(
            model_name='tastingevent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='tastingeventregistration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='tastingeventregistration',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasting_registrations', to='crm.customer', verbose_name='Müşteri'),
        ),
        migrations.AddField(
            model_name='tastingeventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='cellar.tastingevent', verbose_name='Etkinlik'),
        ),
        migrations.AddField(
            model_name='tastingeventregistration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='tastingnote',
            name='author_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasting_notes', to=settings.AUTH_USER_MODEL, verbose_name='Yazan'),
        ),
        migrations.AddField(
            model_name='tastingnote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='tastingnote',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='wine',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='wine',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Silen'),
        ),
        migrations.AddField(
            model_name='wine',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='tastingnote',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasting_notes', to='cellar.wine', verbose_name='Şarap'),
        ),
        migrations.AddField(
            model_name='tastingevent',
            name='wines',
            field=models.ManyToManyField(blank=True, related_name='tasting_events', to='cellar.wine', verbose_name='Şaraplar'),
        ),
        migrations.AddField(
            model_name='privatecellarbottle',
            name='wine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='private_bottles', to='cellar.wine', verbose_name='Şarap'),
        ),
        migrations.AddField(
            model_name='bottleopening',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bottle_openings', to='cellar.wine', verbose_name='Şarap'),
        ),
        migrations.AddField(
            model_name='bottlelot',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='cellar.wine', verbose_name='Şarap'),
        ),
        migrations.AddField(
            model_name='wineclubmembership',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='wineclubmembership',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='club_memberships', to='crm.customer', verbose_name='Müşteri'),
        ),
        migrations.AddField(
            model_name='wineclubmembership',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='wineclubtier',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='wineclubtier',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='wineclubmembership',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='cellar.wineclubtier', verbose_name='Kademe'),
        ),
        migrations.AddField(
            model_name='wineduplicatealert',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='wineduplicatealert',
            name='other_wine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_alerts_as_other', to='cellar.wine', verbose_name='Karşılaştırılan şarap'),
        ),
        migrations.AddField(
            model_name='wineduplicatealert',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_duplicate_alerts', to=settings.AUTH_USER_MODEL, verbose_name='İnceleyen'),
        ),
        migrations.AddField(
            model_name='wineduplicatealert',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='wineduplicatealert',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_alerts', to='cellar.wine', verbose_name='Şarap'),
        ),
        migrations.AddField(
            model_name='winefault',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='winefault',
            name='detected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wine_faults', to=settings.AUTH_USER_MODEL, verbose_name='Tespit eden'),
        ),
        migrations.AddField(
            model_name='winefault',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faults', to='cellar.bottlelot', verbose_name='Parti'),
        ),
        migrations.AddField(
            model_name='winefault',
            name='opening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faults', to='cellar.bottleopening', verbose_name='Açılmış şişe'),
        ),
        migrations.AddField(
            model_name='winefault',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='winefault',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faults', to='cellar.wine', verbose_name='Şarap'),
        ),
        migrations.AddField(
            model_name='wineflight',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='wineflight',
            name='menu_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wine_flight', to='catalog.menuitem', verbose_name='Menü ürünü'),
        ),
        migrations.AddField(
            model_name='wineflight',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='wineflightitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='wineflightitem',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cellar.wineflight', verbose_name='Uçuş'),
        ),
        migrations.AddField(
            model_name='wineflightitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='wineflightitem',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_items', to='cellar.wine', verbose_name='Şarap'),
        ),
        migrations.AddField(
            model_name='winegrapecomposition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='winegrapecomposition',
            name='grape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wines', to='cellar.grapevariety', verbose_name='Üzüm'),
        ),
        migrations.AddField(
            model_name='winegrapecomposition',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='winegrapecomposition',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grape_compositions', to='cellar.wine', verbose_name='Şarap'),
        ),
        migrations.AddField(
            model_name='winepairing',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pairings', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan'),
        ),
        migrations.AddField(
            model_name='winepairing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='winepairing',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wine_pairings', to='catalog.menuitem', verbose_name='Menü ürünü'),
        ),
        migrations.AddField(
            model_name='winepairing',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='winepairing',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='cellar.wine', verbose_name='Şarap'),
        ),
        migrations.AddField(
            model_name='wineproducer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='wineproducer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='wine',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wines', to='cellar.wineproducer', verbose_name='Üretici'),
        ),
        migrations.AddField(
            model_name='winerating',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='winerating',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='winerating',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='cellar.wine', verbose_name='Şarap'),
        ),
        migrations.AddField(
            model_name='wineregion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='wineregion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='cellar.wineregion', verbose_name='Üst bölge'),
        ),
        migrations.AddField(
            model_name='wineregion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='wineproducer',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producers', to='cellar.wineregion', verbose_name='Bölge'),
        ),
        migrations.AddField(
            model_name='wine',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wines', to='cellar.wineregion', verbose_name='Bölge / Apelasyon'),
        ),
        migrations.AddField(
            model_name='grapevariety',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='native_grapes', to='cellar.wineregion', verbose_name='Köken'),
        ),
        migrations.AddField(
            model_name='winestoragelocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='winestoragelocation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='cellar.winestoragelocation', verbose_name='Üst konum'),
        ),
        migrations.AddField(
            model_name='winestoragelocation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='storagereading',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='cellar.winestoragelocation', verbose_name='Konum'),
        ),
        migrations.AddField(
            model_name='privatecellarclient',
            name='allocated_locations',
            field=models.ManyToManyField(blank=True, related_name='private_clients', to='cellar.winestoragelocation', verbose_name='Ayrılan konumlar'),
        ),
        migrations.AddField(
            model_name='privatecellarbottle',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='private_bottles', to='cellar.winestoragelocation', verbose_name='Konum'),
        ),
        migrations.AddField(
            model_name='bottlelot',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='cellar.winestoragelocation', verbose_name='Konum'),
        ),
        migrations.AddConstraint(
            model_name='tastingeventregistration',
            constraint=models.UniqueConstraint(fields=('event', 'customer'), name='uniq_event_customer'),
        ),
        migrations.AddIndex(
            model_name='bottleopening',
            index=models.Index(fields=['status', '-opened_at'], name='opening_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='wineflightitem',
            constraint=models.UniqueConstraint(fields=('flight', 'wine'), name='uniq_flight_wine'),
        ),
        migrations.AddConstraint(
            model_name='winegrapecomposition',
            constraint=models.UniqueConstraint(fields=('wine', 'grape'), name='uniq_wine_grape'),
        ),
        migrations.AddConstraint(
            model_name='winepairing',
            constraint=models.UniqueConstraint(condition=models.Q(('menu_item__isnull', False)), fields=('wine', 'menu_item'), name='uniq_wine_menuitem_pairing'),
        ),
        migrations.AddConstraint(
            model_name='wineregion',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='uniq_region_name_parent'),
        ),
        migrations.AddConstraint(
            model_name='wineproducer',
            constraint=models.UniqueConstraint(fields=('name', 'region'), name='uniq_producer_region'),
        ),
        migrations.AddIndex(
            model_name='wine',
            index=models.Index(fields=['wine_type', 'is_active'], name='wine_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='wine',
            index=models.Index(fields=['vintage'], name='wine_vintage_idx'),
        ),
        migrations.AddConstraint(
            model_name='wine',
            constraint=models.UniqueConstraint(fields=('producer', 'name', 'vintage', 'bottle_size_ml'), name='uniq_wine_producer_name_vintage_size'),
        ),
        migrations.AddConstraint(
            model_name='bottlelot',
            constraint=models.UniqueConstraint(fields=('wine', 'lot_code'), name='uniq_wine_lot_code'),
        ),
        migrations.AddConstraint(
            model_name='bottlelot',
            constraint=models.CheckConstraint(condition=models.Q(('bottles_remaining__lte', models.F('bottles_received'))), name='lot_remaining_lte_received'),
        ),
    ]
