# Generated by Django 5.2.6 on 2026-08-18 05:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('name', models.CharField(max_length=200, verbose_name='Kampanya adı')),
                ('rule_type', models.CharField(choices=[('percent_off', 'Yüzde indirim'), ('amount_off', 'Tutar indirimi'), ('fixed_price', 'Sabit fiyat')], default='percent_off', max_length=20, verbose_name='Kural türü')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Değer')),
                ('starts_on', models.DateField(blank=True, null=True, verbose_name='Başlangıç tarihi')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='Bitiş tarihi')),
                ('starts_at', models.TimeField(blank=True, null=True, verbose_name='Günlük başlangıç saati')),
                ('ends_at', models.TimeField(blank=True, null=True, verbose_name='Günlük bitiş saati')),
                ('weekdays', models.JSONField(blank=True, default=list, verbose_name='Geçerli günler')),
                ('is_active', models.BooleanField(default=True, verbose_name='Etkin')),
                ('requires_approval', models.BooleanField(default=False, help_text='İşaretliyse kampanya yönetici onayı olmadan uygulanmaz.', verbose_name='Onay gerektirir')),
            ],
            options={
                'verbose_name': 'Fiyat kuralı',
                'verbose_name_plural': 'Fiyat kuralları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('yield_portions', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Verim (porsiyon)')),
                ('instructions', models.TextField(blank=True, verbose_name='Hazırlama talimatı')),
                ('plating_notes', models.TextField(blank=True, verbose_name='Sunum notu')),
                ('waste_allowance_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Fire payı (%)')),
            ],
            options={
                'verbose_name': 'Reçete',
                'verbose_name_plural': 'Reçeteler',
            },
        ),
        migrations.CreateModel(
            name='RecipeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Miktar')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Not')),
                ('is_optional', models.BooleanField(default=False, verbose_name='İsteğe bağlı')),
            ],
            options={
                'verbose_name': 'Reçete satırı',
                'verbose_name_plural': 'Reçete satırları',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='Kod')),
                ('name_tr', models.CharField(max_length=100, verbose_name='Ad (TR)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Ad (EN)')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='Simge')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Alerjen',
                'verbose_name_plural': 'Alerjenler',
                'ordering': ['name_tr'],
            },
        ),
        migrations.CreateModel(
            name='DietaryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='Kod')),
                ('name_tr', models.CharField(max_length=100, verbose_name='Ad (TR)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Ad (EN)')),
                ('badge_class', models.CharField(default='bg-success', max_length=40, verbose_name='Rozet sınıfı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Beslenme etiketi',
                'verbose_name_plural': 'Beslenme etiketleri',
                'ordering': ['name_tr'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='Kod')),
                ('name_tr', models.CharField(max_length=120, verbose_name='Ad (TR)')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='Ad (EN)')),
                ('description_tr', models.TextField(blank=True, verbose_name='Açıklama (TR)')),
                ('description_en', models.TextField(blank=True, verbose_name='Açıklama (EN)')),
                ('channel', models.CharField(choices=[('dine_in', 'Salon'), ('bar', 'Bar'), ('takeaway', 'Paket servis'), ('event', 'Etkinlik'), ('all', 'Tümü')], default='all', max_length=20, verbose_name='Satış kanalı')),
                ('preparation_station', models.CharField(choices=[('kitchen', 'Mutfak'), ('bar', 'Bar'), ('wine', 'Şarap / Sommelier'), ('none', 'Hazırlık yok')], default='kitchen', max_length=20, verbose_name='Hazırlık istasyonu')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Etkin')),
                ('show_on_qr_menu', models.BooleanField(default=True, verbose_name='QR menüde göster')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.menucategory', verbose_name='Üst kategori')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Menü kategorisi',
                'verbose_name_plural': 'Menü kategorileri',
                'ordering': ['sort_order', 'name_tr'],
            },
        ),
        migrations.CreateModel(
            name='MenuEngineeringSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('period_start', models.DateField(verbose_name='Dönem başı')),
                ('period_end', models.DateField(verbose_name='Dönem sonu')),
                ('units_sold', models.PositiveIntegerField(default=0, verbose_name='Satış adedi')),
                ('popularity_index', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8, verbose_name='Popülerlik endeksi')),
                ('contribution_margin', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Katkı payı')),
                ('quadrant', models.CharField(choices=[('star', 'Yıldız (yüksek kâr, yüksek satış)'), ('plowhorse', 'At (düşük kâr, yüksek satış)'), ('puzzle', 'Bilmece (yüksek kâr, düşük satış)'), ('dog', 'Köpek (düşük kâr, düşük satış)')], max_length=20, verbose_name='Kadran')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Menü mühendisliği kaydı',
                'verbose_name_plural': 'Menü mühendisliği kayıtları',
                'ordering': ['-period_end', '-contribution_margin'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Silindi')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme zamanı')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Ürün kodu')),
                ('name_tr', models.CharField(db_index=True, max_length=200, verbose_name='Ad (TR)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Ad (EN)')),
                ('description_tr', models.TextField(blank=True, verbose_name='Açıklama (TR)')),
                ('description_en', models.TextField(blank=True, verbose_name='Açıklama (EN)')),
                ('item_type', models.CharField(choices=[('food', 'Yemek'), ('drink', 'İçecek'), ('wine', 'Şarap'), ('wine_glass', 'Kadeh şarap'), ('set_menu', 'Set menü'), ('wine_flight', 'Şarap uçuşu'), ('service', 'Servis / Ücret')], default='food', max_length=20, verbose_name='Tür')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Satış fiyatı')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='KDV oranı (%)')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Reçeteden otomatik hesaplanır; el ile de girilebilir.', max_digits=12, verbose_name='Maliyet')),
                ('cost_is_manual', models.BooleanField(default=False, verbose_name='Maliyet el ile girildi')),
                ('portion_size', models.CharField(blank=True, max_length=60, verbose_name='Porsiyon')),
                ('preparation_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='Hazırlık (dk)')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kalori')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Etkin')),
                ('is_available', models.BooleanField(default=True, help_text='Geçici olarak tükendi/kapalı işaretleyin.', verbose_name='Serviste')),
                ('show_on_qr_menu', models.BooleanField(default=True, verbose_name='QR menüde göster')),
                ('is_chef_recommendation', models.BooleanField(default=False, verbose_name='Şef önerisi')),
                ('is_sommelier_recommendation', models.BooleanField(default=False, verbose_name='Sommelier önerisi')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Sıra')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Görsel')),
                ('tracks_stock', models.BooleanField(default=True, help_text='Kapalıysa satışta stok hareketi oluşturulmaz.', verbose_name='Stoktan düşer')),
                ('allergens', models.ManyToManyField(blank=True, related_name='menu_items', to='catalog.allergen', verbose_name='Alerjenler')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.menucategory', verbose_name='Kategori')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Silen')),
                ('dietary_tags', models.ManyToManyField(blank=True, related_name='menu_items', to='catalog.dietarytag', verbose_name='Beslenme etiketleri')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Menü ürünü',
                'verbose_name_plural': 'Menü ürünleri',
                'ordering': ['category__sort_order', 'sort_order', 'name_tr'],
                'permissions': [('can_change_price', 'Fiyat değiştirebilir'), ('can_manage_promotion', 'Kampanya yönetebilir'), ('view_menu_engineering', 'Menü mühendisliği raporunu görebilir')],
            },
        ),
    ]
