# Generated by Django 5.2.6 on 2026-08-18 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('cellar', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='wine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='cellar.wine', verbose_name='Şarap'),
        ),
        migrations.AddField(
            model_name='menuengineeringsnapshot',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineering_snapshots', to='catalog.menuitem', verbose_name='Menü ürünü'),
        ),
        migrations.AddField(
            model_name='pricerule',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='price_rules', to='catalog.menucategory', verbose_name='Kategoriler'),
        ),
        migrations.AddField(
            model_name='pricerule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='pricerule',
            name='menu_items',
            field=models.ManyToManyField(blank=True, related_name='price_rules', to='catalog.menuitem', verbose_name='Ürünler'),
        ),
        migrations.AddField(
            model_name='pricerule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='menu_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='catalog.menuitem', verbose_name='Menü ürünü'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='recipeline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='recipeline',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='catalog.recipe', verbose_name='Reçete'),
        ),
        migrations.AddField(
            model_name='recipeline',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_lines', to='inventory.stockitem', verbose_name='Stok kalemi'),
        ),
        migrations.AddField(
            model_name='recipeline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['item_type', 'is_active'], name='menuitem_type_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='menuengineeringsnapshot',
            constraint=models.UniqueConstraint(fields=('menu_item', 'period_start', 'period_end'), name='uniq_menu_engineering_period'),
        ),
        migrations.AddConstraint(
            model_name='recipeline',
            constraint=models.UniqueConstraint(fields=('recipe', 'stock_item'), name='uniq_recipe_stockitem'),
        ),
    ]
